server:
  port: 8090
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - 172.23.238.184:9092
      bindings:
        Projects:
          destination: Projects
          content-type: application/json
        Location:
          destination: Location
          content-type: application/json
        Certificates:
          destination: Certificates
          content-type: application/json
        AcademicQualification:
          destination: AcademicQualification
          content-type: application/json
        PersonalInfo:
          destination: PersonalInfo
          content-type: application/json
        Experience:
          destination: Experience
          content-type: application/json
        Skills:
          destination: Skills
          content-type: application/json
  