version: '2.1'

services:
 zuul-service:
    build: zuul-apigateway/
    image: zuul-service
    restart: always
    container_name: zuul
    network_mode: "host"
    hostname: localhost
    ports:
      - 8092:8092
    healthcheck:
      test: "exit 0"
    
 config-service:
    build: config-service/
    image: config-service
    restart: always
    container_name: config
    network_mode: "host"
    hostname: localhost
    ports:
      - 8891:8891
    healthcheck:
      test: "exit 0"

 eureka-service:
    build: eureka-server/
    image: eureka-server
    restart: always
    container_name: eureka
    network_mode: "host"
    hostname: localhost
    ports:
      - 9090:9090
    healthcheck:
      test: "exit 0"
 
 zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    network_mode: "host"
    container_name: zookeeper
    hostname: localhost
    restart: always
    healthcheck:
      test: "exit 0"

 kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_CREATE_TOPICS: "Location:1:1, Certificates:1:1, Academies:1:1, PersonalInfo:1:1, Experience:1:1, Projects:1:1, 
       Skills:1:1, CassandraRegistration:1:1"
    network_mode: "host"
    hostname: localhost
    depends_on:
      - zookeeper
    restart: always
    healthcheck:
      test: "exit 0"
  
 mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=register
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root
    network_mode: "host"
    hostname: localhost
    restart: always
    healthcheck:
      test: "exit 0"

 neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/12345
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
    volumes:
      - ./plugins:/plugins
      - $HOME/neo4j/data:/data
      - ./import:/import  

 mongodb:
   image: mongo
   container_name: "mongodb"
   volumes:
     - /my/own/datadir:/data/db
   ports:
     - 27017:27017
   network_mode: "host"
   hostname: localhost
   restart: always
   healthcheck:
     test: "exit 0"
 
 

 user-service:
    build: user-service/
    image: user-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8081:8081
    container_name: user
    healthcheck:
      test: "exit 0" 

 

 login-service:
    build: login-service/
    image: login-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8082:8082
    container_name: login
    healthcheck:
      test: "exit 0"


 experience-service:
    build: experience-microservice/
    image: experience-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8083:8083
    container_name: exp
    healthcheck:
      test: "exit 0"

 training-service:
    build: training-microservice/
    image: training-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8084:8084
    container_name: training
    healthcheck:
      test: "exit 0"
  
 qual-service:
    build: qualification-microservice/
    image: academy-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8085:8085
    container_name: academy
    healthcheck:
      test: "exit 0"

 location-service:
    build: location-microservice/
    image: location-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8086:8086
    container_name: location
    healthcheck:
      test: "exit 0"

 personalinformation-service:
    build: personalinformation-microservice/
    image: personalinformation-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8087:8087
    container_name: personal
    healthcheck:
      test: "exit 0"

 project-service:
    build: project-microservice/
    image: project-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8088:8088
    container_name: project
    healthcheck:
      test: "exit 0"

 
 skill-service:
    build: skill-microservice/
    image: skill-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8089:8089
    container_name: skill
    healthcheck:
      test: "exit 0"
 
 downstream-service:
    build: downstream-service/
    image: downstream-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8090:8090
    container_name: downstream
    depends_on:
      - mongodb
    healthcheck:
      test: "exit 0"

 index-service:
    build: indexer-service/
    image: indexer-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8091:8091
    container_name: indexer
    depends_on:
      - neo4j
    healthcheck:
      test: "exit 0"

 nlp-service:
    build: nlp-service/
    image: nlp-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8999:8999
    container_name: nlp
    healthcheck:
      test: "exit 0"

 search-service:
    build: search-microservice/
    image: search-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8998:8998
    container_name: search
    healthcheck:
      test: "exit 0"

   

 angular-app:
    build: Angular-project/
    image: angular
    restart: always
    container_name: Angular
    network_mode: "host"
    hostname: localhost
    ports:
      - 4200:4200
    healthcheck:
      test: "exit 0"    
 


