version: '2.1'

services:
 zuul-service:
    build: zuul-apigateway/
    image: zuul-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8092:8092
    healthcheck:
      test: "exit 0"
    
 config-service:
    build: config-service/
    image: config-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8891:8891
    healthcheck:
      test: "exit 0"

 eureka-service:
    build: eureka-server/
    image: eureka-server
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 9090:9090
    healthcheck:
      test: "exit 0"
 
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    network_mode: "host"
    hostname: localhost
    restart: always
    healthcheck:
      test: "exit 0"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_CREATE_TOPICS: "Location:1:1, Certificates:1:1, Academies:1:1, PersonalInfo:1:1, Experience:1:1, Projects:1:1, 
       Skills:1:1, CassandraRegistration:1:1"
    network_mode: "host"
    hostname: localhost
    depends_on:
      - zookeeper
    restart: always
    healthcheck:
      test: "exit 0"
  
   mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=register
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root
    network_mode: "host"
    hostname: localhost
    restart: always
    healthcheck:
      test: "exit 0"

   neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
    volumes:
      - ./plugins:/plugins
      - $HOME/neo4j/data:/data
      - ./import:/import  
 
 

 user-service:
    build: user-service/
    image: user-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8081:8081
    healthcheck:
      test: "exit 0" 

 

 login-service:
    build: login-service/
    image: login-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8082:8082
    healthcheck:
      test: "exit 0"


 experience-service:
    build: experience-microservice/
    image: experience-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8083:8083
    healthcheck:
      test: "exit 0"

 training-service:
    build:training-microservice/
    image:training-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8084:8084
    healthcheck:
      test: "exit 0"
  
 qual-service:
    build: qualification-microservice/
    image: academy-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8085:8085
    healthcheck:
      test: "exit 0"

  location-service:
    build: location-microservice/
    image: location-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8086:8086
    healthcheck:
      test: "exit 0"

  personalinformation-service:
    build: personalinformation-microservice/
    image: personalinformation-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8087:8087
    healthcheck:
      test: "exit 0"

  project-service:
    build: project-microservice/
    image: project-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8088:8088
    healthcheck:
      test: "exit 0"

 
 skill-service:
    build: skill-microservice/
    image: skill-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8089:8089
    healthcheck:
      test: "exit 0"
 
 downstream-service:
    build: downstream-service/
    image: downstream-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8090:8090
    healthcheck:
      test: "exit 0"

 index-service:
    build: indexer-service/
    image: indexer-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8091:8091
    depends_on:
      - neo4j
    healthcheck:
      test: "exit 0"    
 


