spring:
  kafka:
    bootstrap-servers: 172.23.238.163:9092
    consumer:
     group-id: group_json

experienceproducer:
  producer:
    exp: Experience
    
experienceproducer1:
   producer1:
    exp1: ExperienceIndexer123
server:
  port: 8083 
    
    