spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
     group-id: group_json

experienceproducer:
  producer:
    exp: Experience
    
experienceproducer1:
   producer1:
    exp1: Experience1